// ignore_for_file: file_names
// ignore_for_file: library_prefixes
// ignore_for_file: constant_identifier_names
// ignore_for_file: non_constant_identifier_names

const String TXT_PRODUCT_ID = 'Product Id';
const String TXT_DESCRIPTION = 'Description';
const String TXT_DESCRIPTION_2 = 'Extended Description';
const String TXT_DESCRIPTION_3 = 'User\'s Note';
const String TXT_ITEMCODE = 'Item Code';
const String TXT_SEARCH_TEXT = 'Search Text';
const String TXT_UPC = 'Upc';
const String TXT_COST = 'Cost';
const String TXT_PRICE = 'Price';
const String TXT_DEPARTMENT = 'Department';
const String TXT_SECTION = 'Section';
const String TXT_CATEGORY = 'Category';
const String TXT_VENDOR = 'Vendor';
const String TXT_DISCOUNT = 'Discount';
const String TXT_TAX = 'Tax';
const String TXT_MARGIN = 'Margin';
const String TXT_MARKUP = 'Markup';
const String TXT_CREATED_BY = 'Created By/Datetime';
const String TXT_UPDATED_BY = 'Last Updated By/Datetime';
const String TXT_CREATE_DATETIME = 'Created Datetime';
const String TXT_UPDATED_DATETIME = 'Updated Datetime';

const String BTN_CONFIRM = 'Confirm';
const String BTN_YES = 'Yes';
const String BTN_NO = 'No';
const String BTN_NEW_ITEM = 'New Item';
const String BTN_SEARCH = 'Search';
const String BTN_ADD_ITEMCODE = 'Add Item Code';
const String BTN_UPDATE_ITEMCODE = 'Modify Item Code';
const String BTN_ADD_UPC = 'Add Upc';
const String BTN_UPDATE_UPC = 'Modify Upc';
const String BTN_ADD_PRODUCT = 'Add Item';
const String BTN_UPDATE_PRODUCT = 'Update Item';
const String BTN_SAVE = 'Save';
const String BTN_DISMISS = 'Dismiss';
const String BTN_NEW_ITEMCODE = 'New Item Code';

const String HINT_SEARCH_TEXT = 'Enter Your Search Text Here';
const String HINT_DESCRIPTION = 'Enter Description';
const String HINT_DESCRIPTION_2 = 'Enter Extended Description';
const String HINT_DESCRIPTION_3 = 'Enter User Note';
const String HINT_PRODUCT_ID = 'Product Id Will Be Generated By The System';
const String HINT_ITEMCODE = 'Enter Item Code';
const String HINT_UPC = 'Enter Upc';
const String HINT_COST = 'Enter Cost (Numeric Value Only)';
const String HINT_PRICE = 'Enter Price (Numeric Value Only)';
const String HINT_MARGIN = 'Enter Expected Margin (Numeric Value Only And Rounded Percentage)';
const String HINT_MARKUP = 'Enter Expected Markup (Numeric Value Only And Rounded Percentage)';
const String HINT_ITEMCODE_ADD_UPDATE = "This Item Does Not Have ItemCode";

const String VALIDATE_DESCRIPTION = 'Please Provide Description';
const String VALIDATE_COST = 'Please Provide Cost For The Item. Enter 0 if Item Does Not Have Cost';
const String VALIDATE_PRICE = 'Please Provide Price For The Item';